name: Package and Upload Java App to Release

on: workflow_dispatch

jobs:
  package_and_upload:
    runs-on: ubuntu-latest
    
    steps:steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
